use chrono::Utc;

use crate::models::read::ReadResult;

/// Paper data for report rendering.
pub struct ReportPaper {
    pub paper_id: String,
    pub rank: usize,
    pub title: String,
    pub authors: String,
    pub abstract_text: String,
    pub landing_url: Option<String>,
    pub pdf_url: Option<String>,
    pub read_result: Option<ReadResult>,
}

/// Render HTML report.
pub fn render_html(title: &str, papers: &[ReportPaper], run_id: &str) -> String {
    let mut html = format!(
        r#"<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; color: #333; }}
h1 {{ color: #1a1a1a; border-bottom: 2px solid #e0e0e0; padding-bottom: 10px; }}
.paper {{ margin: 20px 0; padding: 15px; border: 1px solid #e0e0e0; border-radius: 8px; }}
.paper h2 {{ margin-top: 0; color: #2c3e50; }}
.authors {{ color: #666; font-style: italic; }}
.abstract {{ color: #555; font-size: 0.95em; }}
.summary {{ background: #f8f9fa; padding: 12px; border-radius: 4px; margin-top: 10px; }}
.links a {{ margin-right: 15px; color: #3498db; text-decoration: none; }}
.links a:hover {{ text-decoration: underline; }}
.footer {{ margin-top: 30px; padding-top: 10px; border-top: 1px solid #e0e0e0; color: #999; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>{title}</h1>
"#
    );

    for paper in papers {
        html.push_str(&format!(
            r#"<div class="paper">
<h2>#{rank}. {title}</h2>
<p class="authors">{authors}</p>
"#,
            rank = paper.rank,
            title = escape_html(&paper.title),
            authors = escape_html(&paper.authors),
        ));

        if let Some(url) = &paper.landing_url {
            html.push_str(&format!(
                r#"<p class="links"><a href="{url}">Paper page</a>"#,
            ));
        }
        if let Some(url) = &paper.pdf_url {
            html.push_str(&format!(
                r#" <a href="{url}">PDF</a>"#,
            ));
        }
        html.push_str("</p>\n");

        if let Some(result) = &paper.read_result {
            html.push_str(&format!(
                r#"<div class="summary">{}</div>"#,
                escape_html(&result.summary)
            ));
        } else {
            html.push_str(r#"<p class="abstract"><em>Summary not available.</em></p>"#);
        }

        html.push_str("</div>\n");
    }

    let now = Utc::now().format("%Y-%m-%d %H:%M UTC");
    html.push_str(&format!(
        r#"<div class="footer">Generated by daily-paper on {now} (run: {run_id})</div>
</body>
</html>"#
    ));

    html
}

fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_basic_report() {
        let papers = vec![
            ReportPaper {
                paper_id: "p1".into(),
                rank: 1,
                title: "Test Paper".into(),
                authors: "Alice Smith".into(),
                abstract_text: "An abstract.".into(),
                landing_url: Some("https://arxiv.org/abs/2301.12345".into()),
                pdf_url: None,
                read_result: None,
            },
        ];

        let html = render_html("Daily Papers", &papers, "test-run-1");
        assert!(html.contains("Test Paper"));
        assert!(html.contains("Alice Smith"));
        assert!(html.contains("#1"));
        assert!(html.contains("test-run-1"));
    }

    #[test]
    fn escape_html_special_chars() {
        assert_eq!(escape_html("<b>bold</b>"), "&lt;b&gt;bold&lt;/b&gt;");
        assert_eq!(escape_html("a & b"), "a &amp; b");
    }
}
