use super::html::ReportPaper;

/// Render plain text report (fallback for non-HTML sinks).
pub fn render_text(title: &str, papers: &[ReportPaper], run_id: &str) -> String {
    let mut text = format!("{}\n{}\n\n", title, "=".repeat(title.len()));

    for paper in papers {
        text.push_str(&format!("#{}. {}\n", paper.rank, paper.title));
        text.push_str(&format!("   Authors: {}\n", paper.authors));

        if let Some(url) = &paper.landing_url {
            text.push_str(&format!("   URL: {}\n", url));
        }

        if let Some(result) = &paper.read_result {
            text.push_str(&format!("\n{}\n", result.summary));
        }

        text.push_str("\n---\n\n");
    }

    text.push_str(&format!(
        "Generated by daily-paper on {} (run: {})\n",
        chrono::Utc::now().format("%Y-%m-%d %H:%M UTC"),
        run_id
    ));

    text
}
